Microverse Portfolio: mobile menu
Fombi-Favour/Microverse-portfolio pull request #10
Opened 2023-05-15 21:05 UTC by Fombi-Favour

In this activity, we: 
- Modified the index.html file
- Modified the style.css file for the menu
- Added an index.js file for interactive style

2023-05-15 21:18 UTC, 1GORDON reviewed
##
## Hi @Fombi-Favour ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [x] Kindly ensure your coding partner contributes to this pull request since this is a pair programming activity.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-15 21:21 UTC, Fombi-Favour commented
Hello

2023-05-16 14:39 UTC, Fombi-Favour commented
My coding partner made some commits and here are those commits.
- [first commit](https://github.com/Fombi-Favour/Microverse-portfolio/commit/23d5f07f3f6887ede8db7ac5edcffeb1e2cb8bc6)
- [second commit](https://github.com/Fombi-Favour/Microverse-portfolio/commit/1103c65d7d0f554af962504e78fc7acd9c485a81)
- [third commit](https://github.com/Fombi-Favour/Microverse-portfolio/commit/0c1b01f8a9ba9a7c08c9891baea0e3b808ec0d54)
- [fourth commit](https://github.com/Fombi-Favour/Microverse-portfolio/commit/ac3339f61c666cbcdf519df81f9beb8d99da403d)

Please kindly consider this 🙏🙏

2023-05-17 08:22 UTC, ahmetbozaci commented
### Hello @Fombi-Favour 
### _This is an additional review as a result of the second opinion request._ 
- You filled out the second opinion form after your partner make changes. Before the code reviewer reviews it your partner only commits. So code reviewer is right to invalidate it.
- Kindly submit it for review again.

___



### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2023-05-17 08:29 UTC, Fombi-Favour commented
Before submitting request for code review, my coding partner made commit.
Here was his first commit before my submission [here!](https://github.com/Fombi-Favour/Microverse-portfolio/pull/10/commits/ac3339f61c666cbcdf519df81f9beb8d99da403d)

After that review, my coding partner and I were trying to solve the problem and there was no way until now. I tried to comment on his review but he didn't reply back.

Please kindly consider this commit 🙏🙏

2023-05-17 08:53 UTC, ahmetbozaci commented
> Before submitting request for code review, my coding partner made commit. Here was his first commit before my submission [here!](https://github.com/Fombi-Favour/Microverse-portfolio/pull/10/commits/ac3339f61c666cbcdf519df81f9beb8d99da403d)
> 
> After that review, my coding partner and I were trying to solve the problem and there was no way until now. I tried to comment on his review but he didn't reply back.
> 
> Please kindly consider this commit praypray

- When working on a collaborative project, it is important to strive for equal contributions. However, this doesn't necessarily mean that the number of commits should be the same. **Your partner has already made more changes, I kindly request you submit your work for review again so that the code reviewer can begin evaluating the entire project.**
- Also ı recommend your partner fix the issue on the github for future projects because he/she isn't on the participant list too.

2023-05-17 08:59 UTC, Fombi-Favour commented
I appreciate that. Thank you 🙏 🙏

2023-05-17 09:23 UTC, Davidosky007 requested changes
Hi @Fombi-Favour 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* Basic JavaScript syntax used 👍 
* Events used 👍 
* Good looking readme 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 09:23 UTC, Davidosky007 commented on index.html
> +          <img src="./assets/menu.png" id="menu" alt="logo" onclick="showMenu()" />
* Currently when I click on the hamburger icon on mobile it doesn't show the mobile menu dropdown, kindly fix this

2023-05-17 09:46 UTC, KayLemba approved these changes
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @Fombi-Favour        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] linters are passing
- [x] Professional README 💯
- [x] Mobile Menu workimg as intended 🥇 
- [x] Nice UI💯 
 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

2023-05-17 09:50 UTC, merged