Microverse Portfolio project: finish mobile version
Fombi-Favour/Microverse-portfolio pull request #2
Opened 2023-04-27 20:30 UTC by Fombi-Favour

In this activity, we:
- Updated the index.html file
- Update the style.css file
- Completed the mobile version

2023-04-27 20:51 UTC, Johnadibe reviewed
Hi @Fombi-Favour,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that does not pass linter check for CSS. Please make sure that all linter checks are passed.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-27 21:04 UTC, V-Blaze requested changes
Hi @Fombi-Favour  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![dcentl8-9b96e129-9725-401b-ac34-2feb990202a0](https://user-images.githubusercontent.com/107632780/229646232-19bbafea-ca96-4b36-ad5d-1d64c00d667c.gif)

## Invalid Code Review Request

## You have submitted a project that has some of the important sections of the readme file missing. According to Microverse all the sections of your readme file must be present and filled with content before requesting for review. Currently, your readme file does not have the `Future Feature` section, Please include this in your readme file and also add at least 2 features that could be added to your project in the future. :zap: 
- [ ] I'll also point out here that the link to the license page in your readme is broken, Please look into this too. :+1: :smile: 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-27 22:22 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @Fombi-Favour   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
 :heavy_check_mark: Linters are passing.
:heavy_check_mark: You have a good code structure.
:heavy_check_mark: Linters are green
 
 ## Required Changes 

- [ ] Check Under the review

 ## Optional suggestions 

- [ ] Kindly remove all comments from the template in your `README` , it makes your  project looks unprofessional :wink: 

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 22:22 UTC, Alfredbis29 commented on index.html
> +            <button type="button" class="btn-detail contact">Get in touch</button>
- [ ] I can see that you did a great job on this project, but they're still to improve on something for your project to look more professional, I can see that you forget to put a `placeholder` in your form to refer a user what to complete in the form, kindly add it for a good user experience,  kindly fix this :point_down: don't forget to follow figma guidelines, make sure you put the same `font` as for Figma

Your design
![Screenshot from 2023-04-28 00-03-06](https://user-images.githubusercontent.com/88894525/235001073-4df6cc69-2f2e-432d-9c4d-e0c5e3eb6c4c.png)

Figma Design
![Screenshot from 2023-04-27 23-56-38](https://user-images.githubusercontent.com/88894525/235001147-4fdde430-42d4-4d2d-b9db-1276eee4c8e3.png)

2023-04-27 22:22 UTC, Alfredbis29 commented on README.md
- [ ] I noticed that one of the links you included, specifically the M.I.T license link, is broken and no longer functional.
As you know, links are an essential part of any project, and it's crucial to ensure that they are functional and lead to the intended content. In this case, the broken link may hinder the ability of others to access important information related to your project. Kindly fix this :point_down: 
![Screenshot from 2023-04-28 00-11-25](https://user-images.githubusercontent.com/88894525/235003087-6b93b29d-d4e9-410a-8853-19e97fc006dc.png)

2023-04-28 06:34 UTC, abdulhamiid approved these changes
# :green_circle:  Approved! :partying_face:
Hi @Fombi-Favour 👋, 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

As part of professional [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- Let's always use descriptive commit messages - each commit message should be meaningful and small enough to describe it in one sentence. 🛠

 Here are some examples of descriptive commits:

<img width="822" alt="descriptive_commits_example" src="https://user-images.githubusercontent.com/78251927/235071480-1fac76d1-7dd2-47d4-9ca3-832a689e00d4.png">


Here are some commits that are not descriptive:

![not_descriptive_commits](https://user-images.githubusercontent.com/78251927/235071471-7924173b-db8d-4700-9ff4-5c613c084030.png)

IMPORTANT: As it is not easy to change commit history, kindly correct this behavior in the future. 🛠💪

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 06:35 UTC, merged